[build]
builder = "nixpacks"
buildCommand = "npm install --platform=linux --arch=x64 && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install --platform=linux --arch=x64"]

[phases.build]
cmds = ["npm run build"] 