[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["rm -rf node_modules package-lock.json", "npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"] 